# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'OnHealth' do

use_frameworks!

pod 'Firebase', '>= 2.5.1'
pod 'SwiftRequest', '0.0.4'

end

